use_frameworks!

platform :ios, '13.0'

target 'UIViewPreviewWrapper_Example' do
  pod 'UIViewPreviewWrapper', :path => '../'

  target 'UIViewPreviewWrapper_Tests' do
    inherit! :search_paths

    
  end
end
